# tmux options
set-option -g mouse on

# Use C-Space as prefix instead of C-b
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @plugin 'whame/tmux-modal'
set -g @modal-keybindings-conf '~/.config/tmux/modal-keybindings.conf'

run '~/.tmux/plugins/tpm/tpm'